### ISSUE TITLE
something more

### ISSUE THREAD

**Issue by ghost** [krypt0nn/warp-gui#1]
will add something to change between modes? like dns with warp or without? this app is excellent and beautiful

**Comment by krypt0nn** [comment]
Glad to read it, thank

I wrote this app based on my `electron-blank-app` repository. Today I added SASS and TypeScript support, tomorrow I'm going to make a flatpak builder (now it doesn't work) and release this program to the flathub

After this, I want to fix some issues with application builds and add settings. So yes, I'm going to develop this application and make it better

I'm extremely new in JS and Electron, the platform I used to write this app, so it may take some time for me to get how things works
